# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set the environment variables
ENV POSTGRES_DB userbase
ENV POSTGRES_USER postgres_user
ENV POSTGRES_PASSWORD postgres_password

# Expose the default PostgreSQL port
EXPOSE 5432
